# Generated by Django 5.1.7 on 2025-03-13 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("faculty", models.CharField(blank=True, max_length=255, null=True)),
                ("specialty", models.CharField(blank=True, max_length=255, null=True)),
                ("end_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_entries",
                        to="resumes.resume",
                    ),
                ),
            ],
        ),
    ]
