# Generated by Django 5.1.7 on 2025-03-14 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_education"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="end_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Год окончания"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="faculty",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Факультет"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="institution",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Учебное заведение"
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education_entries",
                to="resumes.resume",
                verbose_name="Резюме",
            ),
        ),
        migrations.AlterField(
            model_name="education",
            name="specialty",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Специальность"
            ),
        ),
    ]
