# Generated by Django 5.1.7 on 2025-03-14 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0003_alter_education_end_year_alter_education_faculty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="education_entries",
                to="resumes.resume",
            ),
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=255, verbose_name="Компания")),
                (
                    "position",
                    models.CharField(max_length=255, verbose_name="Должность"),
                ),
                ("date_from", models.DateField(verbose_name="Дата начала работы")),
                (
                    "date_to",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания работы"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_entries",
                        to="resumes.resume",
                    ),
                ),
            ],
        ),
    ]
