# Generated by Django 5.1.7 on 2025-03-16 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0004_alter_education_resume_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=100, verbose_name="Навык")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("B", "Базовый"),
                            ("I", "Средний"),
                            ("A", "Продвинутый"),
                        ],
                        max_length=1,
                        verbose_name="Уровень",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills_entries",
                        to="resumes.resume",
                    ),
                ),
            ],
        ),
    ]
